version: '3.6'
services:
  productdb:
    image: mongo
    ports: 
      - "27017:27017"
    restart: always

  orderdb:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Azure123
      MYSQL_DATABASE: orderdb
      MYSQL_USER: username
      MYSQL_PASSWORD: Azure
    volumes:
      - ./init:/docker-entrypoint-initdb.d 